apiVersion: v2
name: traefik-routes
description: >
  Helm chart to generate Traefik Gateway HTTPRoutes and Middlewares
  dynamically from a simple declarative YAML structure (applications + routes).

type: application
version: 0.1.0
appVersion: "1.0"

keywords:
  - traefik
  - gateway-api
  - httproute
  - middleware
  - kubernetes
  - routing

home: https://github.com/rridane/helm-traefik-routes
maintainers:
  - name: Rida Ridane
    email: rridane@rr-dev.com
    url: https://github.com/rridane

sources:
  - https://doc.traefik.io/traefik/routing/providers/kubernetes-gateway/
  - https://gateway-api.sigs.k8s.io/

dependencies: []
