apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}-agent
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
    component: otel-agent
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-agent
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-agent
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 30
      containers:
        - name: otel-agent
          image: {{ .Values.image }}
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            - "--config=/etc/otelcol-contrib/config.yaml"
            {{- range .Values.featureGates }}
            - "{{ . }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /etc/otelcol-contrib/config.yaml
              subPath: config.yaml
              readOnly: true

            # Logs containers sur le node
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true

            # Journald du node
            - name: varlogjournal
              mountPath: /var/log/journal
              readOnly: true

            # kubelet SSL
            - name: kubelet-pki
              mountPath: /etc/kubernetes/pki
              readOnly: true

      volumes:
        - name: data
          configMap:
            name: otel-agent-configmap

        - name: varlogpods
          hostPath:
            path: /var/log/pods/

        - name: varlogjournal
          hostPath:
            path: /var/log/journal/

        - name: kubelet-pki
          hostPath:
            path: /etc/kubernetes/pki/
