---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: {{ $.Values.namespace }}
  labels:
    {{- range $key, $value := $.Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: 80
  selector:
    {{- range $key, $value := $.Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
---