---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- range $key, $value := $.Values.agent.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    app.kubernetes.io/version: {{ $.Values.agent.image.tag }}
  name: parca-agent
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    matchLabels:
      {{- range $key, $value := $.Values.agent.labels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key, $value := $.Values.agent.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        app.kubernetes.io/version: {{ $.Values.agent.image.tag }}
    spec:
      containers:
        - args:
            - --http-address=:7071
            - --node=$(NODE_NAME)
            - --config-path=/etc/parca-agent/parca-agent.yaml
            - --remote-store-address=parca.parca.svc.cluster.local:{{ $.Values.server.service.port }}
            - --remote-store-insecure
            {{- range .Values.agent.extraArgs }}
            - {{ . }}
            {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: {{ $.Values.agent.image.repository }}:{{ $.Values.agent.image.tag }}
          name: parca-agent
          ports:
            - containerPort: {{ .Values.agent.service.port | default 7071 }}
              name: http
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /run
              name: run
            - mountPath: /boot
              name: boot
              readOnly: true
            - mountPath: /lib/modules
              name: modules
            - mountPath: /sys/kernel/debug
              name: debugfs
            - mountPath: /sys/fs/cgroup
              name: cgroup
            - mountPath: /sys/fs/bpf
              name: bpffs
            - mountPath: /etc/parca-agent
              name: config
            - mountPath: /var/run/dbus/system_bus_socket
              name: dbus-system
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: parca-agent
      tolerations:
        - operator: Exists
      volumes:
        - emptyDir: {}
          name: tmp
        - hostPath:
            path: /run
          name: run
        - hostPath:
            path: /boot
          name: boot
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroup
        - hostPath:
            path: /lib/modules
          name: modules
        - hostPath:
            path: /sys/fs/bpf
          name: bpffs
        - hostPath:
            path: /sys/kernel/debug
          name: debugfs
        - configMap:
            name: parca-agent
          name: config
        - hostPath:
            path: /var/run/dbus/system_bus_socket
          name: dbus-system
---